### ISSUE TITLE
Does not work with 3.3.0.14

### ISSUE THREAD

**Issue by cy8aer** [lainwir3d/sailfish-rpn-calculator#5]
... because SailfishOS updated to Python 3.8.1!

**Comment by sbridger** [comment]
Module mpmath missing in 4.0.18.

https://forum.sailfishos.org/t/missing-python-module-how-to-install/6195

```
[nemo@Sailfish ~]$ harbour-rpncalc
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Got library name:  "/usr/lib/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
[D] unknown:0 - "PyOtherSide error: Traceback (most recent call last):\n\n  File \"/usr/share/harbour-rpncalc/python/rpncalc_engine.py\", line 11, in <module>\n    import rpncalc_mpmath_backend as mpmathBackend\n\n  File \"/usr/share/harbour-rpncalc/python/rpncalc_mpmath_backend.py\", line 2, in <module>\n    import mpmath\n\nModuleNotFoundError: No module named 'mpmath'\n"
[W] unknown:0 - Unhandled PyOtherSide error: Cannot import module: rpncalc_engine (Traceback (most recent call last):

  File "/usr/share/harbour-rpncalc/python/rpncalc_engine.py", line 11, in <module>
    import rpncalc_mpmath_backend as mpmathBackend

  File "/usr/share/harbour-rpncalc/python/rpncalc_mpmath_backend.py", line 2, in <module>
    import mpmath

ModuleNotFoundError: No module named 'mpmath'
)```

**Comment by sbridger** [comment]
_mpmath_ was all that was missing: 

`devel-su pkcon install python3-pip`
`pip install --user mpmath`
`

**Comment by cy8aer** [comment]
This is only a fixup and cannot be expected from an end user

Two ways to get it running:

* Include mpmath into the code (see https://gitlab.com/cy8aer/podqast how to do this)
* Build an python environment (see https://gitlab.com/cy8aer/bluepill nio branch tools dir how to do this) - this should be done if the python libraries do have binaries. But it looks like it is not the case with mpmath.
